format_version: 10
pipelines:
  unicorn-openfire-parent-pom-snapshot:
    group: Unicorn-Openfire-Notifications-Snapshot
    template: maven-snapshot-pom
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    secure_variables:
      ARTIFACTORY_USERNAME: AES:aPO62lFjZkm8pmmGsp0dvw==:ORVHqPUpN1gyiceACeaFqcLmuLuTGYqdyC/1Sb/Gzbc=
      ARTIFACTORY_PASSWORD: AES:qs6mIvRIy/oJ+Jr1klBuNQ==:N2qeyCdxHWF0K8gkSOI1zsR3h34vGFNizPYTXWfw+78LX1PspgkhoUjadlIQWM5Qkb9nTV/Uk57UtJHCh9o8/g==
    materials:
      unicorn-openfire-parent-pom-snapshot-scm:
        scm: 9b7cb333-41cb-4f95-af02-cbefe0ba4b8f
        destination: openfire
      tools:
        git: git@github.gamesys.co.uk:client-delivery-platform/unicorn-openfire-notifications.git
        includes:
        - ci-tools/*
        shallow_clone: false
        auto_update: true
        branch: master
        destination: tools
